export const TOP_SYMBOLS = [
    // STOCKS (Top 150)
    { symbol: "AAPL", name: "Apple Inc.", type: "Stock" },
    { symbol: "MSFT", name: "Microsoft Corporation", type: "Stock" },
    { symbol: "GOOGL", name: "Alphabet Inc.", type: "Stock" },
    { symbol: "AMZN", name: "Amazon.com Inc.", type: "Stock" },
    { symbol: "TSLA", name: "Tesla, Inc.", type: "Stock" },
    { symbol: "NVDA", name: "NVIDIA Corporation", type: "Stock" },
    { symbol: "META", name: "Meta Platforms, Inc.", type: "Stock" },
    { symbol: "BRK-B", name: "Berkshire Hathaway Inc.", type: "Stock" },
    { symbol: "UNH", name: "UnitedHealth Group Incorporated", type: "Stock" },
    { symbol: "JNJ", name: "Johnson & Johnson", type: "Stock" },
    { symbol: "V", name: "Visa Inc.", type: "Stock" },
    { symbol: "WMT", name: "Walmart Inc.", type: "Stock" },
    { symbol: "PG", name: "Procter & Gamble Company", type: "Stock" },
    { symbol: "JPM", name: "JPMorgan Chase & Co.", type: "Stock" },
    { symbol: "MA", name: "Mastercard Incorporated", type: "Stock" },
    { symbol: "HD", name: "The Home Depot, Inc.", type: "Stock" },
    { symbol: "CVX", name: "Chevron Corporation", type: "Stock" },
    { symbol: "PFE", name: "Pfizer Inc.", type: "Stock" },
    { symbol: "ABBV", name: "AbbVie Inc.", type: "Stock" },
    { symbol: "KO", name: "The Coca-Cola Company", type: "Stock" },
    { symbol: "PEP", name: "PepsiCo, Inc.", type: "Stock" },
    { symbol: "BAC", name: "Bank of America Corporation", type: "Stock" },
    { symbol: "AVGO", name: "Broadcom Inc.", type: "Stock" },
    { symbol: "COST", name: "Costco Wholesale Corporation", type: "Stock" },
    { symbol: "MRK", name: "Merck & Co., Inc.", type: "Stock" },
    { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", type: "Stock" },
    { symbol: "MCD", name: "McDonald's Corporation", type: "Stock" },
    { symbol: "CSCO", name: "Cisco Systems, Inc.", type: "Stock" },
    { symbol: "ABT", name: "Abbott Laboratories", type: "Stock" },
    { symbol: "ACN", name: "Accenture plc", type: "Stock" },
    { symbol: "ADBE", name: "Adobe Inc.", type: "Stock" },
    { symbol: "AMD", name: "Advanced Micro Devices, Inc.", type: "Stock" },
    { symbol: "DIS", name: "The Walt Disney Company", type: "Stock" },
    { symbol: "LIN", name: "Linde plc", type: "Stock" },
    { symbol: "NFLX", name: "Netflix, Inc.", type: "Stock" },
    { symbol: "CRM", name: "Salesforce, Inc.", type: "Stock" },
    { symbol: "TXN", name: "Texas Instruments Incorporated", type: "Stock" },
    { symbol: "DHR", name: "Danaher Corporation", type: "Stock" },
    { symbol: "PM", name: "Philip Morris International Inc.", type: "Stock" },
    { symbol: "VZ", name: "Verizon Communications Inc.", type: "Stock" },
    { symbol: "NEE", name: "NextEra Energy, Inc.", type: "Stock" },
    { symbol: "RTX", name: "Raytheon Technologies Corporation", type: "Stock" },
    { symbol: "CMCSA", name: "Comcast Corporation", type: "Stock" },
    { symbol: "AMAT", name: "Applied Materials, Inc.", type: "Stock" },
    { symbol: "INTC", name: "Intel Corporation", type: "Stock" },
    { symbol: "HON", name: "Honeywell International Inc.", type: "Stock" },
    { symbol: "LOW", name: "Lowe's Companies, Inc.", type: "Stock" },
    { symbol: "PGR", name: "The Progressive Corporation", type: "Stock" },
    { symbol: "SPGI", name: "S&P Global Inc.", type: "Stock" },
    { symbol: "IBM", name: "International Business Machines Corporation", type: "Stock" },
    { symbol: "UNP", name: "Union Pacific Corporation", type: "Stock" },
    { symbol: "CAT", name: "Caterpillar Inc.", type: "Stock" },
    { symbol: "GS", name: "The Goldman Sachs Group, Inc.", type: "Stock" },
    { symbol: "ELV", name: "Elevance Health Inc.", type: "Stock" },
    { symbol: "LMT", name: "Lockheed Martin Corporation", type: "Stock" },
    { symbol: "AMT", name: "American Tower Corporation", type: "Stock" },
    { symbol: "DE", name: "Deere & Company", type: "Stock" },
    { symbol: "GE", name: "General Electric Company", type: "Stock" },
    { symbol: "QCOM", name: "QUALCOMM Incorporated", type: "Stock" },
    { symbol: "INTU", name: "Intuit Inc.", type: "Stock" },
    { symbol: "PLD", name: "Prologis, Inc.", type: "Stock" },
    { symbol: "AXP", name: "American Express Company", type: "Stock" },
    { symbol: "BA", name: "The Boeing Company", type: "Stock" },
    { symbol: "CVS", name: "CVS Health Corporation", type: "Stock" },
    { symbol: "AMGN", name: "Amgen Inc.", type: "Stock" },
    { symbol: "MDLZ", name: "Mondelez International, Inc.", type: "Stock" },
    { symbol: "TJX", name: "The TJX Companies, Inc.", type: "Stock" },
    { symbol: "ADP", name: "Automatic Data Processing, Inc.", type: "Stock" },
    { symbol: "GILD", name: "Gilead Sciences, Inc.", type: "Stock" },
    { symbol: "ADK", name: "Autodesk, Inc.", type: "Stock" },
    { symbol: "ISRG", name: "Intuitive Surgical, Inc.", type: "Stock" },
    { symbol: "BKNG", name: "Booking Holdings Inc.", type: "Stock" },
    { symbol: "SYK", name: "Stryker Corporation", type: "Stock" },
    { symbol: "MDT", name: "Medtronic plc", type: "Stock" },
    { symbol: "CI", name: "Cigna Group", type: "Stock" },
    { symbol: "LRCX", name: "Lam Research Corporation", type: "Stock" },
    { symbol: "MMC", name: "Marsh & McLennan Companies, Inc.", type: "Stock" },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc.", type: "Stock" },
    { symbol: "CB", name: "Chubb Limited", type: "Stock" },
    { symbol: "ADI", name: "Analog Devices, Inc.", type: "Stock" },
    { symbol: "SCHW", name: "The Charles Schwab Corporation", type: "Stock" },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated", type: "Stock" },
    { symbol: "ZTS", name: "Zoetis Inc.", type: "Stock" },
    { symbol: "MU", name: "Micron Technology, Inc.", type: "Stock" },
    { symbol: "EL", name: "The Estée Lauder Companies Inc.", type: "Stock" },
    { symbol: "IBM", name: "IBM", type: "Stock" },
    { symbol: "BSX", name: "Boston Scientific Corporation", type: "Stock" },
    { symbol: "C", name: "Citigroup Inc.", type: "Stock" },
    { symbol: "EOG", name: "EOG Resources, Inc.", type: "Stock" },
    { symbol: "MPC", name: "Marathon Petroleum Corporation", type: "Stock" },
    { symbol: "CME", name: "CME Group Inc.", type: "Stock" },
    { symbol: "FIS", name: "Fidelity National Information Services, Inc.", type: "Stock" },
    { symbol: "PANW", name: "Palo Alto Networks, Inc.", type: "Stock" },
    { symbol: "SNPS", name: "Synopsys, Inc.", type: "Stock" },
    { symbol: "KLAC", name: "KLA Corporation", type: "Stock" },
    { symbol: "CDNS", name: "Cadence Design Systems, Inc.", type: "Stock" },
    { symbol: "ETN", name: "Eaton Corporation plc", type: "Stock" },
    { symbol: "SLB", name: "Schlumberger Limited", type: "Stock" },
    { symbol: "PXD", name: "Pioneer Natural Resources Company", type: "Stock" },
    { symbol: "MO", name: "Altria Group, Inc.", type: "Stock" },

    // CRYPTO (Top 80)
    { symbol: "BTC-USD", name: "Bitcoin", type: "Crypto" },
    { symbol: "ETH-USD", name: "Ethereum", type: "Crypto" },
    { symbol: "USDT-USD", name: "Tether", type: "Crypto" },
    { symbol: "BNB-USD", name: "BNB", type: "Crypto" },
    { symbol: "SOL-USD", name: "Solana", type: "Crypto" },
    { symbol: "XRP-USD", name: "XRP", type: "Crypto" },
    { symbol: "USDC-USD", name: "USDC", type: "Crypto" },
    { symbol: "ADA-USD", name: "Cardano", type: "Crypto" },
    { symbol: "DOGE-USD", name: "Dogecoin", type: "Crypto" },
    { symbol: "SHIB-USD", name: "Shiba Inu", type: "Crypto" },
    { symbol: "AVAX-USD", name: "Avalanche", type: "Crypto" },
    { symbol: "DOT-USD", name: "Polkadot", type: "Crypto" },
    { symbol: "LINK-USD", name: "Chainlink", type: "Crypto" },
    { symbol: "TRX-USD", name: "TRON", type: "Crypto" },
    { symbol: "MATIC-USD", name: "Polygon", type: "Crypto" },
    { symbol: "BCH-USD", name: "Bitcoin Cash", type: "Crypto" },
    { symbol: "LTC-USD", name: "Litecoin", type: "Crypto" },
    { symbol: "NEAR-USD", name: "NEAR Protocol", type: "Crypto" },
    { symbol: "UNI7083-USD", name: "Uniswap", type: "Crypto" },
    { symbol: "ICP-USD", name: "Internet Computer", type: "Crypto" },
    { symbol: "LEO-USD", name: "UNUS SED LEO", type: "Crypto" },
    { symbol: "DAI-USD", name: "Dai", type: "Crypto" },
    { symbol: "ETC-USD", name: "Ethereum Classic", type: "Crypto" },
    { symbol: "APT-USD", name: "Aptos", type: "Crypto" },
    { symbol: "RNDR-USD", name: "Render", type: "Crypto" },
    { symbol: "XMR-USD", name: "Monero", type: "Crypto" },
    { symbol: "XLM-USD", name: "Stellar", type: "Crypto" },
    { symbol: "ATOM-USD", name: "Cosmos", type: "Crypto" },
    { symbol: "OKB-USD", name: "OKB", type: "Crypto" },
    { symbol: "ARB-USD", name: "Arbitrum", type: "Crypto" },
    { symbol: "STX-USD", name: "Stacks", type: "Crypto" },
    { symbol: "FIL-USD", name: "Filecoin", type: "Crypto" },
    { symbol: "HBAR-USD", name: "Hedera", type: "Crypto" },
    { symbol: "CRO-USD", name: "Cronos", type: "Crypto" },
    { symbol: "IMX-USD", name: "Immutable", type: "Crypto" },
    { symbol: "VET-USD", name: "VeChain", type: "Crypto" },
    { symbol: "MKR-USD", name: "Maker", type: "Crypto" },
    { symbol: "GRT-USD", name: "The Graph", type: "Crypto" },
    { symbol: "INJ-USD", name: "Injective", type: "Crypto" },
    { symbol: "THETA-USD", name: "Theta Network", type: "Crypto" },
    { symbol: "FTM-USD", name: "Fantom", type: "Crypto" },
    { symbol: "RUNE-USD", name: "THORChain", type: "Crypto" },
    { symbol: "OP-USD", name: "Optimism", type: "Crypto" },
    { symbol: "PEPE-USD", name: "Pepe", type: "Crypto" },
    { symbol: "FLOKI-USD", name: "Floki", type: "Crypto" },
    { symbol: "BONK-USD", name: "Bonk", type: "Crypto" },
    { symbol: "WIF-USD", name: "dogwifhat", type: "Crypto" },
    { symbol: "BSV-USD", name: "Bitcoin SV", type: "Crypto" },

    // COMMODITIES (Top 20)
    { symbol: "GC=F", name: "Gold", type: "Commodity" },
    { symbol: "SI=F", name: "Silver", type: "Commodity" },
    { symbol: "CL=F", name: "Crude Oil", type: "Commodity" },
    { symbol: "NG=F", name: "Natural Gas", type: "Commodity" },
    { symbol: "BZ=F", name: "Brent Crude Oil", type: "Commodity" },
    { symbol: "HG=F", name: "Copper", type: "Commodity" },
    { symbol: "PA=F", name: "Palladium", type: "Commodity" },
    { symbol: "PL=F", name: "Platinum", type: "Commodity" },
    { symbol: "ZC=F", name: "Corn", type: "Commodity" },
    { symbol: "ZS=F", name: "Soybean", type: "Commodity" },
    { symbol: "ZW=F", name: "Wheat", type: "Commodity" },
    { symbol: "KC=F", name: "Coffee", type: "Commodity" },
    { symbol: "CC=F", name: "Cocoa", type: "Commodity" },
    { symbol: "SB=F", name: "Sugar", type: "Commodity" },
    { symbol: "CT=F", name: "Cotton", type: "Commodity" },
    { symbol: "OJ=F", name: "Orange Juice", type: "Commodity" },
    { symbol: "LBS=F", name: "Lumber", type: "Commodity" },
    { symbol: "LH=F", name: "Lean Hogs", type: "Commodity" },
    { symbol: "FC=F", name: "Feeder Cattle", type: "Commodity" },
    { symbol: "LC=F", name: "Live Cattle", type: "Commodity" },
];
